name: Auto Assign Issue

on:
  issues:
    types: [opened]

  jobs:
    assign:
      runs-on: ubuntu-latest
      steps:
        - name: Assign issue author
          uses: pozil/auto-assign-issue@v1
          with:
            assignees: ${{ github.actor }}